# Chatbot Project

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel('Book1.xlsx')

In [3]:
df.head()

Questions  \
0                      Hello   
1         What is your name?   
2          What can you do?    
3  How is the weather today?   
4  How is the weather today?   

                                             Answers  
0      Hello! Welcome to Weather Prediction Chatbot.  
1                   I am Windy, the Weather Chatbot.  
2  I can answer all your questions related to wea...  
3                                    It's hot today.  
4                              It's so cold outside.

In [4]:
df.shape

(18, 2)

In [5]:
df.dtypes

Questions    object
Answers      object
dtype: object

In [6]:
df['Questions']=df['Questions'].str.lower()

In [7]:
df.dropna(inplace=True)

In [8]:
df =df.drop_duplicates()

In [9]:
from nltk.tokenize import word_tokenize

In [10]:
exemple="I am, a king!"
exemple_tok = word_tokenize(exemple)
exemple_tok

['I', 'am', ',', 'a', 'king', '!']

In [11]:
" ".join(exemple_tok)

'I am , a king !'

In [12]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [13]:
def remove_punct(text):
    res=" "
    for ele in text:
        if ele not in string.punctuation:
            res+=ele
    return res

In [14]:
remove_punct(exemple)

' I am a king'

In [15]:
exemple

'I am, a king!'

In [16]:
exemple=remove_punct(exemple)
exemple

' I am a king'

In [17]:
df['Questions']=df.Questions.apply(remove_punct)

In [18]:
from nltk.corpus import stopwords

stop=set(stopwords.words('english'))
stop

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [19]:
def remove_stopword(text):
        text = ' '.join([word for word in text.split() if word not in stop])
        return text

In [20]:
remove_stopword('i am a strong king')

'strong king'

In [21]:
list1 = []

In [22]:
for t in df.Questions:    
    list1.append(remove_stopword(t))

In [23]:
list1

['hello',
 'name',
 '',
 'weather today',
 'weather today',
 'weather today',
 'weather today',
 'weather today',
 'weather today',
 'raining',
 'raining',
 'cold',
 'cold',
 'hot',
 'hot',
 'windy',
 'windy']

In [24]:
df['Questions'] = pd.DataFrame({'Questions':list1})

In [25]:
df.head()

Questions                                            Answers
0          hello      Hello! Welcome to Weather Prediction Chatbot.
1           name                   I am Windy, the Weather Chatbot.
2                 I can answer all your questions related to wea...
3  weather today                                    It's hot today.
4  weather today                              It's so cold outside.

In [26]:
import nltk
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [27]:
lemmatizer.lemmatize('kid')

'kid'

In [28]:
def lemm(text):
    return lemmatizer.lemmatize(text)

In [29]:
df.Questions=df.Questions.apply(lemm)

In [30]:
df.Questions

0             hello
1              name
2                  
3     weather today
4     weather today
5     weather today
6     weather today
7     weather today
8     weather today
9           raining
10          raining
11             cold
12             cold
13              hot
14              hot
15            windy
16            windy
Name: Questions, dtype: object

In [31]:
corpus=df['Questions'].values
corpus

array(['hello', 'name', '', 'weather today', 'weather today',
       'weather today', 'weather today', 'weather today', 'weather today',
       'raining', 'raining', 'cold', 'cold', 'hot', 'hot', 'windy',
       'windy'], dtype=object)

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
bw_vect = CountVectorizer()
bw_fit=bw_vect.fit(corpus)
bw_corpus = bw_fit.transform(corpus)

In [33]:
bw_corpus.shape

(17, 8)

In [34]:
bw_fit.get_feature_names()

C:\Users\HP\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['cold', 'hello', 'hot', 'name', 'raining', 'today', 'weather', 'windy']

In [35]:
bw_corpus.toarray()

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [36]:
cv_data=pd.DataFrame(bw_corpus.toarray(),columns=bw_fit.get_feature_names())
cv_data

cold  hello  hot  name  raining  today  weather  windy
0      0      1    0     0        0      0        0      0
1      0      0    0     1        0      0        0      0
2      0      0    0     0        0      0        0      0
3      0      0    0     0        0      1        1      0
4      0      0    0     0        0      1        1      0
5      0      0    0     0        0      1        1      0
6      0      0    0     0        0      1        1      0
7      0      0    0     0        0      1        1      0
8      0      0    0     0        0      1        1      0
9      0      0    0     0        1      0        0      0
10     0      0    0     0        1      0        0      0
11     1      0    0     0        0      0        0      0
12     1      0    0     0        0      0        0      0
13     0      0    1     0        0      0        0      0
14     0      0    1     0        0      0        0      0
15     0      0    0     0        0      0        0      1
16     0      0    0     0        0      0        0      1

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
tf_vect = TfidfVectorizer(max_features=5000)
tfidf_fit=tf_vect.fit(corpus)
tfidf_corpus= tfidf_fit.transform(corpus)

In [39]:
tfidf_fit.get_feature_names()

C:\Users\HP\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['cold', 'hello', 'hot', 'name', 'raining', 'today', 'weather', 'windy']

In [40]:
tfidf_data=pd.DataFrame(tfidf_corpus.toarray(),columns=tfidf_fit.get_feature_names())
tfidf_data

cold  hello  hot  name  raining     today   weather  windy
0    0.0    1.0  0.0   0.0      0.0  0.000000  0.000000    0.0
1    0.0    0.0  0.0   1.0      0.0  0.000000  0.000000    0.0
2    0.0    0.0  0.0   0.0      0.0  0.000000  0.000000    0.0
3    0.0    0.0  0.0   0.0      0.0  0.707107  0.707107    0.0
4    0.0    0.0  0.0   0.0      0.0  0.707107  0.707107    0.0
5    0.0    0.0  0.0   0.0      0.0  0.707107  0.707107    0.0
6    0.0    0.0  0.0   0.0      0.0  0.707107  0.707107    0.0
7    0.0    0.0  0.0   0.0      0.0  0.707107  0.707107    0.0
8    0.0    0.0  0.0   0.0      0.0  0.707107  0.707107    0.0
9    0.0    0.0  0.0   0.0      1.0  0.000000  0.000000    0.0
10   0.0    0.0  0.0   0.0      1.0  0.000000  0.000000    0.0
11   1.0    0.0  0.0   0.0      0.0  0.000000  0.000000    0.0
12   1.0    0.0  0.0   0.0      0.0  0.000000  0.000000    0.0
13   0.0    0.0  1.0   0.0      0.0  0.000000  0.000000    0.0
14   0.0    0.0  1.0   0.0      0.0  0.000000  0.000000    0.0
15   0.0    0.0  0.0   0.0      0.0  0.000000  0.000000    1.0
16   0.0    0.0  0.0   0.0      0.0  0.000000  0.000000    1.0

In [52]:
test='Is it raining outside?'
tfidf_test=tfidf_fit.transform([test])

In [53]:
tfidf_test.shape

(1, 8)

In [54]:
mask=tfidf_test.toarray()!=0
m=mask[0]
m

array([False, False, False, False,  True, False, False, False])

In [55]:
tfidf_test.toarray()[mask]

array([1.])

In [56]:
tfidf_data.columns[m]

Index(['raining'], dtype='object')

In [57]:
from sklearn.metrics.pairwise import cosine_similarity
cm=cosine_similarity(tfidf_test, tfidf_corpus)
cm[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.])

In [58]:
lis1 = cm[0].tolist()

In [59]:
lis1

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [60]:
from bs4 import BeautifulSoup
import requests
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}


def weather(city):
    city = city.replace(" ", "+")
    res = requests.get(
        f'https://www.google.com/search?q={city}&oq={city}&aqs=chrome.0.35i39l2j0l4j46j69i60.6128j1j7&sourceid=chrome&ie=UTF-8', headers=headers)

    soup = BeautifulSoup(res.text, 'html.parser')
    location = soup.select('#wob_loc')[0].getText().strip()
    time = soup.select('#wob_dts')[0].getText().strip()
    info = soup.select('#wob_dc')[0].getText().strip()
    weather = soup.select('#wob_tm')[0].getText().strip()
    print(location)
    print(time)
    print(info)
    print(weather+"°C")


In [62]:
try:
    if 1 in lis1:
        city = input("Enter the Name of City -> ")
        city = city + " weather"
        weather(city)
    else:
        print("I am Windy, the Weather Chatbot. I can answer all your questions related to weather predictions.")
except Exception as e:
    print("I am Windy, the Weather Chatbot. I can answer all your questions related to weather predictions.")

Enter the Name of City -> delhi
Delhi
Sunday, 2:00 pm
Haze
25°C
